# Stock Strategy
### Based on 5 years of data obtained from yahoo finance

#### Sources

- https://github.com/kunalkini15/technical_indicators_lib
- https://github.com/Crypto-toolbox/pandas-technical-indicators/blob/master/technical_indicators.py
- https://www.investopedia.com/

### To do

- add to github, version control
- remove old functions
- create a new function that takes an OHLC df and modifies it with all the indicators

_____

## Import modules

In [1]:
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from datetime import datetime
import seaborn as sns

In [2]:
from technical_indicators_lib.indicators import (
    ADI, ATR, BollingerBands, CCI, CMF, CHO, CHV, DC, DPO, EMV, EMA, FI, KC, KST, MI, MED, MOM,
    MFI, MACD, NVI, OBV, PVT, PC, PO, ROC, ROCV, RSI, SMA, VLT, StochasticKAndD,
    Trix, TR, TSI, TYP, VHF, VO, WCL)

adi = ADI()
atr = ATR()
bb = BollingerBands()
cci = CCI()
cmf = CMF()
cho = CHO()
chv = CHV()
dc = DC()
dpo = DPO()
emv = EMV()
ema = EMA()
fi = FI()
kc = KC()
kst = KST()
mi = MI()
mem = MED()
mom = MOM()
mfi = MFI()
macd = MACD()
nvi = NVI()
obv = OBV()
pvt = PVT()
pc = PC()
po = PO()
roc = ROC()
rocv = ROCV()
rsi = RSI()
sma = SMA()
vlt = VLT()
stochastic_k_and_d = StochasticKAndD()
trix = Trix()
tr = TR()
tsi = TSI()
typ = TYP()
vhf = VHF()
vo = VO()
wcl = WCL()

## Get data from YahooFinance API

In [3]:
n = yf.Ticker('QQQ')
s = yf.Ticker('SPY')
d = yf.Ticker('DIA')

In [4]:
nasdaq = n.history(period='5y')
sp500 = s.history(period='5y')
dow = d.history(period='5y')

In [5]:
indices_dict = {'NASDAQ': nasdaq, 'S&P500': sp500, 'DJIA': dow}

In [6]:
# make column names lowercase
for name, df in indices_dict.items():
    df.columns = map(str.lower, df.columns)

In [19]:
nasdaq.head(100)

,open,high,low,close,volume,dividends,stock splits,MA_5d,MA_8d,MA_10d,...,LONG_EMA,SHORT_EMA,MACD,MACD_signal_line,GAIN,LOSS,AVG_GAIN,AVG_LOSS,RS,RSI
Date,,,,,,,,,,,,,,,,,,,,,
2016-03-28,103.265090,103.284295,102.650646,102.833061,13892300,0.0,0,NaN,NaN,NaN,...,102.833061,102.833061,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN
2016-03-29,102.641051,104.551587,102.468238,104.484383,29963900,0.0,0,NaN,NaN,NaN,...,103.690478,103.727527,0.037049,0.020583,1.651321,0.000000,NaN,NaN,NaN,NaN
2016-03-30,105.108444,105.646080,104.772413,104.993233,23807200,0.0,0,NaN,NaN,NaN,...,104.158545,104.221532,0.062987,0.037962,0.508850,0.000000,NaN,NaN,NaN,NaN
2016-03-31,104.916407,105.310039,104.676390,104.839600,21447200,0.0,0,NaN,NaN,NaN,...,104.348938,104.416632,0.067694,0.048033,0.000000,0.153633,NaN,NaN,NaN,NaN
2016-04-01,104.205966,105.991697,104.061954,105.953293,26389000,0.0,0,104.620714,NaN,NaN,...,104.720995,104.834137,0.113143,0.067402,1.113693,0.000000,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-08-10,112.617710,112.646588,111.963124,112.261543,14688400,0.0,0,112.172977,111.758561,111.567483,...,109.450016,111.207180,1.757164,1.703448,0.000000,0.288780,0.330181,0.125825,2.624122,72.407113
2016-08-11,112.646590,112.983516,112.415562,112.742859,12969800,0.0,0,112.452141,111.912584,111.773485,...,109.694070,111.443438,1.749368,1.712632,0.481316,0.000000,0.350333,0.109049,3.212625,76.261833
2016-08-12,112.550328,112.829491,112.425189,112.819862,19379000,0.0,0,112.533002,112.182123,111.963121,...,109.925733,111.655196,1.729463,1.715998,0.077003,0.000000,0.313889,0.094509,3.321262,76.858612
2016-08-15,112.964245,113.561076,112.925739,113.301163,11777800,0.0,0,112.735150,112.466096,112.142170,...,110.175888,111.908422,1.732534,1.719305,0.481300,0.000000,0.336210,0.081908,4.104747,80.410390
2016-08-16,113.089406,113.099027,112.656219,112.675476,14161400,0.0,0,112.760181,112.632151,112.343362,...,110.361127,112.026430,1.665303,1.708505,0.000000,0.625687,0.291382,0.154412,1.887049,65.362554

## Define Indicator Functions

In [8]:
# moving average
def moving_average(df, n):
    '''Calculate the moving average of closing price over n days'''
    name = 'MA_' + str(n) + 'd'
    df[name] = df['close'].rolling(window=n, min_periods=n).mean()
    return df

In [ ]:
# exponential moving average
def exponential_moving_average(df, n):
    '''Calculate the exponential moving average over n days '''
    name = str(n) + 'd_EMA'
    df[name] = df['Close'].ewm(span=n, min_periods=n).mean()
    return df

In [ ]:
# on balance volume
def on_balance_volume(df):
    '''Calculate On-Balance Volume'''
    df['OBV'] = np.where(df['Close'] > df['Close'].shift(1), 
                         df['Volume'], 
                         np.where(df['Close'] < df['Close'].shift(1),
                        -df['Volume'], 0)).cumsum()
    return df

In [ ]:
# momentum
def momentum(df, n):
    '''Calculate momentum over n days'''
    name = str(n) + 'd_M'
    df[name] = df['Close'].diff(n)
    return df

In [ ]:
# rate of change
def rate_of_change(df, n):
    '''Calculate rate of change over n days'''
    name = str(n) + 'd_ROC'
    df[name] = df['Close'].diff(n-1) / df['Close'].shift(n-1)
    return df

In [ ]:
# true range
def true_range(df, n):
    '''Calculate true range over n days'''
    name = str(n) + 'd_TR'
    df[name] = max(df)

## Calculate Indicators for each df

In [9]:
# calculate moving averages for each df
d = [5, 8, 10, 13, 20, 21, 34, 50, 55, 89, 100]
for df in indices_dict.values():
    for day in d:
        moving_average(df, day)

In [11]:
# calculate EMA for each df
d_ema = [5, 12, 20, 26, 50, 200]
for df in indices_dict.values():
    for day in d_ema:
        df = ema.get_value_df(df, time_period=day)
        col_name = 'EMA_' + str(day) + 'd'
        df.rename(columns = {'EMA': col_name}, inplace=True)

In [13]:
# calculate OBV for each df
for df in indices_dict.values():
    df = obv.get_value_df(df)

In [15]:
# calculate ADI
for df in indices_dict.values():
    df = adi.get_value_df(df)

In [16]:
# calculate MACD
for df in indices_dict.values():
    df = macd.get_value_df(df)

In [17]:
# calculate RSI
for df in indices_dict.values():
    df = rsi.get_value_df(df)

C:\Users\jmfin\Anaconda3\envs\finance\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

### Candle Charts

In [ ]:
def candle_plot(df):
    fig = go.Figure(data=[go.Candlestick(x=df.index,
                                        open=df['Open'],
                                        high=df['High'],
                                        low=df['Low'],
                                        close=df['Close'])])
    fig.show()

In [ ]:
for name, df in indices_dict.items():
    print(name)
    candle_plot(df)